#!/usr/bin/env python3
"""Machine-written rotation drivers: a kit and a Rust driver per champion,
written by a cheap model from the champion's dossier and admitted only after
they compile and pass the fight checks.

  registry                 rewrite engine/src/generated/mod.rs from the driver
                           files beside it
  check <slug> | --all     the fight checks on an admitted (or named) driver, or
                           on every admitted one: run it after the checks change
  write <slug>... [--blind] [--workers 3] [--model sonnet] [--effort medium]
                           have the model write data/builds/<slug>.json and
                           engine/src/generated/<slug>.rs: each candidate is
                           compiled and checked in a private copy of the
                           engine, the compiler's and the checks' complaints go
                           back to the model (--rounds), and what passes is
                           copied into the tree. --blind writes a champion that
                           already has a hand-written driver under the name
                           <slug>_blind, never showing the model that driver.
                           --repair starts from the admitted kit and driver and
                           the checks they fail (--failing: every such driver)
                           instead of from nothing; --force rewrites from nothing.
  compare <slug>           a blind driver against the hand-written one over a
                           sample of item builds (damage, kill time, how alike
                           the two rank the builds)

A generated driver implements the same `Driver` trait as the hand-written
ones (jobs/kit-driver-guide.md is what the model is told); the engine runs
them all behind one vtable (engine/src/dyn_driver.rs). Stdlib only.
"""

import argparse
import concurrent.futures
import json
import math
import os
import random
import re
import shutil
import subprocess
import sys
import tempfile
import threading
import time

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, "jobs"))
sys.path.append(BASE_DIR)  # builds.py; `check --so-dir` puts a candidate engine ahead of it
import kit_sources as ks  # noqa: E402

ENGINE_DIR = os.path.join(BASE_DIR, "engine")
GENERATED_DIR = os.path.join(ENGINE_DIR, "src", "generated")
GUIDE_PATH = os.path.join(BASE_DIR, "jobs", "kit-driver-guide.md")
HAND_WRITTEN = ("kayle", "vladimir", "twitch", "kassadin")
# a hand-written kit in progress elsewhere (the survival model): not written over
RESERVED = ("drmundo",)
_print_lock = threading.Lock()


def say(msg):
    with _print_lock:
        print(f"{time.strftime('%H:%M:%S')} {msg}", flush=True)


# ---------------------------------------------------------------------------
# the registry: engine/src/generated/mod.rs
# ---------------------------------------------------------------------------

def driver_names(gen_dir=GENERATED_DIR):
    return sorted(f[:-3] for f in os.listdir(gen_dir) if f.endswith(".rs") and f != "mod.rs")


def registry_text(names):
    mods = "".join(f"pub mod {n};\n" for n in names)
    arms = "".join(
        f'        "{n}" => {n}::GenDriver::new(kit, sheet, level, ranks, prestacked)\n'
        f"            .map(|d| Box::new(d) as Box<dyn DriverObj>),\n" for n in names)
    listed = ", ".join(f'"{n}"' for n in names)
    return f'''//! GENERATED by jobs/kit_driver.py (`registry`) from the files in this
//! directory: do not edit. One module per machine-written driver; each
//! exports `pub struct GenDriver` implementing `crate::fight::Driver`.

use crate::dyn_driver::DriverObj;
use crate::fight::Driver;
use crate::kit::Kit;
use crate::num::Ranks;
use crate::sheet::Sheet;

{mods}
pub const NAMES: [&str; {len(names)}] = [{listed}];

#[allow(unused_variables)]
pub fn build(name: &str, kit: &Kit, sheet: &Sheet, level: i64, ranks: Ranks, prestacked: bool)
    -> Result<Box<dyn DriverObj>, String> {{
    match name {{
{arms}        _ => Err(format!("no generated driver for '{{name}}'")),
    }}
}}
'''


def write_registry(gen_dir=GENERATED_DIR):
    names = driver_names(gen_dir)
    with open(os.path.join(gen_dir, "mod.rs"), "w") as f:
        f.write(registry_text(names))
    return names


def is_manaless(slug):
    """The wiki's resource is not Mana: the item pool drops the mana items."""
    return ks.load_sources(slug)["wiki"]["champion"].get("resource") != "Mana"


def cmd_annotate(args):
    """Facts a generated kit takes from the archive rather than from the model:
    "manaless", which the item pool reads (`write` sets it too)."""
    changed = 0
    for name in driver_names():
        path = os.path.join(BASE_DIR, "data", "builds", f"{name}.json")
        if name.endswith("_blind") or not os.path.exists(path):
            continue
        with open(path) as f:
            kit = json.load(f)
        if not kit.get("generated"):
            continue
        manaless = is_manaless(name)
        if bool(kit.get("manaless")) != manaless:
            kit["manaless"] = manaless
            ks.write_json(path, kit)
            changed += 1
    print(f"{changed} kits updated")


def cmd_registry(args):
    names = write_registry()
    print(f"{len(names)} generated drivers: {', '.join(names) or '-'}")


# ---------------------------------------------------------------------------
# inputs: the champion's base stats, dossier and archived sources
# ---------------------------------------------------------------------------

def ensure_snapshot(slug):
    """The champion's base-stat snapshot (lol.py builds fetch-champion)."""
    import builds
    for patch in reversed(builds.champion_patches()):
        if os.path.isdir(os.path.join(builds.CHAMPIONS_DIR, patch, slug)):
            return
    subprocess.run([sys.executable, os.path.join(BASE_DIR, "lol.py"), "builds", "fetch-champion",
                    slug], check=True, capture_output=True, text=True, cwd=BASE_DIR)


def attack_block(slug):
    """attack.windupFraction and attack.ranged from Riot's character file. The
    windup is 30% plus the file's attack cast offset where it has one, and
    attack cast time over attack total time where it states those instead
    (older champions: Rakan 0.27 / 1.575; the two agree where the wiki gives
    both forms, Vex 0.25 / 1.6 = 0.3 - 0.14375)."""
    import builds
    champ = builds.load_champion(slug)
    riot = champ["riot"] or {}
    rng = riot.get("attackRange", champ["dd"]["stats"]["attackrange"])
    attack = {}
    try:
        with open(os.path.join(ks.source_dir(slug), "bin.json")) as f:
            record = next(v for v in json.load(f).values()
                          if isinstance(v, dict) and v.get("__type") == "CharacterRecord")
        attack = record.get("basicAttack") or {}
    except (SystemExit, OSError, StopIteration):
        pass
    if "attackDelayCastOffsetPercent" in riot:
        windup = 0.3 + riot["attackDelayCastOffsetPercent"]
    elif "mAttackDelayCastOffsetPercent" in attack:
        windup = 0.3 + attack["mAttackDelayCastOffsetPercent"]
    elif attack.get("mAttackCastTime") and attack.get("mAttackTotalTime"):
        windup = attack["mAttackCastTime"] / attack["mAttackTotalTime"]
    else:
        hand = os.path.join(BASE_DIR, "data", "builds", f"{slug}.json")
        if os.path.exists(hand):  # a snapshot from before riot.json: the hand kit states it
            with open(hand) as f:
                windup = json.load(f)["attack"]["windupFraction"]
        else:
            windup = 0.3  # the file states neither: no offset
    return {"windupFraction": round(windup, 5), "ranged": rng > 325}


def numbers_in(node, out):
    if isinstance(node, bool):
        return
    if isinstance(node, (int, float)):
        out.add(float(node))
    elif isinstance(node, str):
        for m in re.findall(r"(?<![\w.])-?\d+(?:\.\d+)?", node):
            out.add(float(m))
    elif isinstance(node, list):
        for v in node:
            numbers_in(v, out)
    elif isinstance(node, dict):
        for v in node.values():
            numbers_in(v, out)


def source_numbers(slug):
    """Every number the dossier, the numbers sheet or the wiki text states."""
    src = ks.load_sources(slug)
    with open(os.path.join(ks.DOSSIERS_DIR, f"{slug}.json")) as f:
        dossier = json.load(f)
    out = set()
    numbers_in(dossier, out)
    numbers_in(src["sheet"], out)
    numbers_in(src["wiki"], out)
    return out


# ---------------------------------------------------------------------------
# static checks on what the model wrote
# ---------------------------------------------------------------------------

ALLOWED_LITERALS = {0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 100.0, 0.5, 1e-9}
FORBIDDEN = [
    (r"\bunsafe\b", "`unsafe`"), (r"\b(std|core|alloc)::", "a std:: path"),
    (r"macro_rules!", "a macro"), (r"\binclude(_str|_bytes)?!", "include!"),
    (r"\benv!|option_env!", "env!"), (r"\bextern\b", "`extern`"), (r"#!\[", "a crate attribute"),
    (r"^\s*(pub\s+)?mod\s+\w+", "a module"), (r"\.max\(|\.min\(", ".max()/.min(): use pymax/pymin"),
    (r"mul_add|\.powi\(|\.powf\(", "mul_add/powi/powf"), (r"\bprintln!|\beprintln!|\bdbg!", "printing"),
]


def strip_comments_and_strings(src):
    src = re.sub(r"//[^\n]*", "", src)
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    return re.sub(r'"(?:\\.|[^"\\])*"', '""', src)


def lint_driver(src):
    errors = []
    code = strip_comments_and_strings(src)
    for need, what in ((r"pub struct GenDriver\b", "`pub struct GenDriver`"),
                       (r"impl Driver for GenDriver\b", "`impl Driver for GenDriver`"),
                       (r"\bs0\b", "the pristine state copy `s0`"),
                       (r"self\.s\s*=\s*self\.s0", "`reset` as `self.s = self.s0;`")):
        if not re.search(need, code):
            errors.append(f"driver: missing {what}")
    for pat, what in FORBIDDEN:
        if re.search(pat, code, re.M):
            errors.append(f"driver: {what} is not allowed")
    for line in code.splitlines():
        if re.match(r"\s*use\s+", line) and not re.match(r"\s*use crate::(fight|fx|kit|num|sheet)\b", line):
            errors.append(f"driver: import not allowed: {line.strip()}")
    bad = set()
    for m in re.finditer(r"(?<![\w.])(\d+(?:\.\d+)?(?:e-?\d+)?)(?:_?(?:f64|i64|u8|u32|usize|u16))?(?![\w.])", code):
        try:
            v = float(m.group(1))
        except ValueError:
            continue
        if v not in ALLOWED_LITERALS:
            bad.add(m.group(1))
    if bad:
        errors.append("driver: game numbers must come from the kit by path, not be written in the "
                      f"Rust: {', '.join(sorted(bad))}")
    return errors


def lint_kit(kit, name, known):
    errors = []
    if not isinstance(kit, dict):
        return ["kit: must be a JSON object"]
    if kit.get("champion") != name:
        errors.append(f'kit: "champion" must be "{name}"')
    if kit.get("generated") is not True or kit.get("reviewed") is not False:
        errors.append('kit: needs "generated": true and "reviewed": false')
    if sorted(kit.get("maxOrder") or []) != ["E", "Q", "W"]:
        errors.append('kit: "maxOrder" must order Q, W and E')
    notes = kit.get("notes")
    if not isinstance(notes, list) or len(notes) < 2 or not all(isinstance(n, str) for n in notes):
        errors.append('kit: "notes" must list the rotation rules and assumptions')
    if "attack" in kit and kit["attack"] != {"never": True}:
        errors.append('kit: "attack" may only be {"never": true} (the script fills the rest)')
    ab = kit.get("abilities")
    if not isinstance(ab, dict) or sorted(ab) != ["E", "Q", "R", "W"]:
        errors.append('kit: "abilities" must have exactly Q, W, E, R')
        ab = {}
    for slot, block in ab.items():
        extra = set(block) - {"name", "cooldownS"} - ({"shred"} if slot == "Q" else set())
        if extra:
            errors.append(f"kit: abilities.{slot} may hold only name and cooldownS "
                          f"(move {sorted(extra)} under gen.{slot})")
        if not isinstance(block.get("cooldownS"), list):
            errors.append(f"kit: abilities.{slot}.cooldownS must be a by-rank list")
    if not isinstance(kit.get("gen"), dict):
        errors.append('kit: needs "gen"')
    assumed = {a.get("path") for a in kit.get("assumed") or [] if isinstance(a, dict) and a.get("why")}

    def walk(node, path):
        if isinstance(node, dict):
            for k, v in node.items():
                walk(v, f"{path}.{k}")
        elif isinstance(node, list):
            for v in node:
                walk(v, path)
        elif isinstance(node, (int, float)) and not isinstance(node, bool):
            if path in assumed or any(path.startswith(a + ".") for a in assumed if a):
                return
            v = float(node)
            if not any(math.isclose(v * k, x, rel_tol=1e-6, abs_tol=1e-9)
                       for k in (1, 100, 0.01) for x in known | {0.0, 1.0}):
                errors.append(f"kit: {path} = {node} is in neither the dossier, the sheet nor the "
                              'wiki: use the stated number, or list the path in "assumed" with why')
    walk(kit.get("gen") or {}, "gen")
    for slot, block in ab.items():
        walk(block.get("cooldownS"), f"abilities.{slot}.cooldownS")
        walk(block.get("shred"), f"abilities.{slot}.shred")
    return errors[:25]


# ---------------------------------------------------------------------------
# fight checks (run in a subprocess against a candidate's own engine build)
# ---------------------------------------------------------------------------

ITEM_SETS = {  # names of the builds pool (builds.DEFAULT_POOL)
    "ap": ["rabadon's deathcap", "luden's echo", "shadowflame", "liandry's torment"],
    "ad crit": ["infinity edge", "the collector", "lord dominik's regards", "phantom dancer"],
    "on-hit": ["blade of the ruined king", "nashor's tooth", "guinsoo's rageblade", "kraken slayer"],
    "haste": ["spear of shojin", "cosmic drive", "navori flickerblade", "muramana"],
    "bruiser": ["trinity force", "sundered sky", "black cleaver", "titanic hydra"],
}
PRESETS = {"squishy": (2800, 110, 60, 8.0), "bruiser": (3800, 180, 120, 12.0),
           "tank": (4800, 220, 160, 15.0)}


# The builds a full search finds when casts cost no time: everything that
# lands in the first instant, item actives included (2026-09-20: ten champions
# killed the squishy at 0.00 s with builds like these).
BURST_SETS = {
    "AP burst": ["sorcerer's shoes", "rabadon's deathcap", "void staff", "shadowflame",
                 "hextech gunblade", "luden's echo"],
    "AD burst": ["sorcerer's shoes", "hextech gunblade", "lord dominik's regards",
                 "youmuu's ghostblade", "profane hydra", "umbral glaive"],
}
CAST_GRID_S = 0.01  # the cast-time probe reads the fight's timeline at this step


def cast_floor(cast_time):
    """The shortest cast time a dossier's `castTime` states for an ability's
    first cast, 0.0 when it has none. The wiki's template can list several: a
    cast time that shrinks with attack speed counts as its shortest, a recast's
    does not count, and an ability whose first form has none is instant."""
    if not isinstance(cast_time, dict):
        return 0.0
    v = cast_time.get("value")
    if isinstance(v, bool) or not isinstance(v, (int, float)) or v <= 0:
        return 0.0
    quote = str(cast_time.get("quote") or "")
    if re.match(r"\s*\{\{(dv|tt)\|\s*(\{\{tt\|\s*)?none\b", quote, re.I):
        return 0.0
    stated = [float(m) for m in re.findall(r"(?<![\w.])\d+(?:\.\d+)?", quote)]
    return min([x for x in stated if 0.05 <= x <= v] + [float(v)])


def sheet_cast_times(slug):
    """{slot: seconds} from Riot's own file (`mCastTime`, which kit_sources
    carries into the numbers sheet). The wiki states a cast time for more
    abilities than this does, but for a handful it says nothing at all and
    this is what there is."""
    out = {}
    try:
        slots = ks.load_sources(slug)["sheet"]["slots"]
    except (SystemExit, OSError, KeyError):
        return out
    for slot in "QWER":
        for e in slots.get(slot) or []:
            v = e.get("castTime") if isinstance(e, dict) else None
            if isinstance(v, (int, float)) and not isinstance(v, bool) and v > 0:
                out[slot] = float(v)
                break
    return out


def cast_floors(kit, dossier, slug=None):
    """{slot: seconds} for the abilities that have a cast time: the wiki's, as
    the dossier records it. Where the wiki says nothing at all (not "none" —
    nothing), Riot's own file fills in. Either way the kit overrides one by
    listing `gen.<slot>.castTimeS` under "assumed" (another form is the one
    cast, the effect starts with the cast): then the kit's number is used."""
    assumed = {a.get("path") for a in kit.get("assumed") or [] if isinstance(a, dict) and a.get("why")}
    riot = sheet_cast_times(slug) if slug else {}
    floors = {}
    for slot in "QWER":
        ab = (dossier.get("abilities") or {}).get(slot)
        floor = cast_floor(ab.get("castTime")) if isinstance(ab, dict) else 0.0
        if floor == 0 and not isinstance((ab or {}).get("castTime"), dict):
            floor = riot.get(slot, 0.0)
        if f"gen.{slot}.castTimeS" in assumed:
            own = ((kit.get("gen") or {}).get(slot) or {}).get("castTimeS")
            own = [own] if isinstance(own, (int, float)) and not isinstance(own, bool) else own
            if isinstance(own, list) and own and all(isinstance(x, (int, float)) for x in own):
                floor = float(min(own))
        if floor > 0:
            floors[slot] = floor
    return floors


def lint_cast_times(kit, dossier, driver_rs, slug):
    """Every ability the sources give a cast time MUST carry it in the kit and
    be read from there by the driver. The opening check below only catches
    casts that overlap each other, so a lone cast that costs nothing slips
    past it (Diana's Q, 2026-09-20): 133 of 367 such abilities were free."""
    errors = []
    unused = kit.get("unused") or {}
    gen = kit.get("gen") or {}
    for slot, secs in sorted(cast_floors(kit, dossier, slug).items()):
        if slot in unused:
            continue
        named = [k for k in (gen.get(slot) or {}) if re.search(r"cast.*time", k, re.I)]
        read = re.search(rf'kit\.\w+\("gen\.{slot}\.[A-Za-z]*[Cc]ast[Tt]ime\w*"', driver_rs)
        if named and read:
            continue
        why = ("the kit does not carry it" if not named else
               f"the kit has gen.{slot}.{named[0]} but the driver never reads it")
        errors.append(
            f"{slot} has a {secs:g} s cast time and {why}, so the driver casts it for free. Put the "
            f"number at gen.{slot}.castTimeS, read it in `new` with kit.num(\"gen.{slot}.castTimeS\"), "
            f"and call `self.busy_for(e, ...)` with it after the cast (the guide's 'Cast times'). If "
            f"the driver never casts {slot} at all, say so in the kit: \"unused\": {{\"{slot}\": "
            f"\"why\"}}. If it really is instant as your driver casts it, write the cast time you use "
            f"at gen.{slot}.castTimeS anyway (0 is allowed) and list that path under \"assumed\" with "
            f"the reason.")
    return errors[:6]


def first_landings(run, floors):
    """{slot: seconds}: when each ability with a cast time first shows damage,
    read off fights of growing length (`run(duration)` -> a fight's result)."""
    landed = {}
    horizon = sum(floors.values()) + 0.5
    for k in range(int(round(horizon / CAST_GRID_S)) + 1):
        t = round(k * CAST_GRID_S, 2)
        for label, dmg in run(t)["breakdown"].items():
            if dmg > 0 and label[:1] in floors and label[:1] not in landed \
                    and re.match(r"[QWER]( |$)", label):
                landed[label[0]] = t
        if len(landed) == len(floors):
            break
    return landed


def cast_time_errors(landed, floors, opening):
    """Casts go one after another (the guide's 'Cast times', the hand-written
    kits' rule): a cast takes effect as it starts and keeps the champion busy
    for its cast time. So of the abilities that have landed by a time T, all
    but the one cast last were cast AND finished inside T. Damage may land long
    after its cast, so the order of the casts is unknown: the longest cast
    counts as the last one, which makes this a condition no correct driver can
    fail (it misses a cast begun inside another whose damage lands later)."""
    for t in sorted(set(landed.values())):
        done = sorted((s for s in landed if landed[s] <= t), key=lambda s: (landed[s], s))
        need = sum(floors[s] for s in done) - max(floors[s] for s in done)
        if need > t + 1e-9:
            times = ", ".join(f"{s} {floors[s]:g} s" for s in done)
            return [f"cast times are not respected ({opening}): {t:.2f} s into the fight "
                    f"{', '.join(done)} have all dealt damage, but casts go one after another and the "
                    f"ones before the last take {need:g} s (cast times per the dossier: {times}). A cast "
                    "with a cast time keeps the champion busy until it ends: no other cast and no "
                    "attack starts inside it (the guide's 'Cast times'). Keep ONE `busy_until` in the "
                    "state, report every cast (q_at and the cast events) at "
                    "`pymax(pymax(ready, e.st.t), self.s.busy_until)`, and after each cast set "
                    "`busy_until = t + its cast time` and hold the next attack to it. If an ability "
                    "really is instant as cast here (another form is the one cast, it can be cast "
                    "during other casts), write the cast time you use at gen.<slot>.castTimeS and list "
                    "that path under \"assumed\" with the reason."]
    return []


class Fights:
    def __init__(self, kit, stats_slug):
        import builds
        self.b = builds
        self.kit = kit
        self.champ = builds.load_champion(stats_slug)
        _, self.pool = builds.load_items()
        self.idx = builds.item_index(self.pool)
        self.effects = builds.load_item_effects()
        self.order = builds.kit_max_order(kit)

    def ids(self, tokens):
        return [t if isinstance(t, int) else self.b.resolve_item(self.pool, self.idx, t)
                for t in tokens]

    def run(self, level, tokens, hp, armor, mr, duration, use_ult=True):
        ids = self.ids(tokens)
        sheet = self.b.resolve_stats(self.champ, level, ids, self.pool, self.effects, kit=self.kit)
        return self.b.simulate(sheet, self.kit, self.b.merge_effects(ids, self.effects), level,
                               self.b.skill_ranks(level, self.order), hp, armor, mr, duration,
                               use_ult=use_ult)


def fight_checks(kit, stats_slug, dossier):
    """(errors, facts): what is wrong with the fights a kit + driver produce."""
    errors, facts = [], {}
    f = Fights(kit, stats_slug)
    big = (30_000, 100, 100)  # outlasts 15 s without blowing up %-health damage

    def attempt(label, *a, **kw):
        try:
            return f.run(*a, **kw)
        except BaseException as e:  # a Rust panic surfaces as PanicException
            errors.append(f"fight failed ({label}): {type(e).__name__}: {str(e)[:400]}")
            return None

    for level in (1, 6, 11, 16, 18):
        for ult in (True, False):
            attempt(f"level {level}, no items, ult {ult}", level, [], *big, 15.0, use_ult=ult)
    for name, items in ITEM_SETS.items():
        for pname, (hp, ar, mr, dur) in PRESETS.items():
            attempt(f"level 16, {name} items vs {pname}", 16, items, hp, ar, mr, dur)
    if errors:
        return errors[:6], facts
    base = f.run(16, [], *big, 15.0)
    again = f.run(16, [], *big, 15.0)
    if base["total"] != again["total"]:
        errors.append("the same fight gave two different totals: the driver is not deterministic")
    total = base["total"]
    facts = {"nakedL16": {"total": round(total), "dps": round(base["dps"], 1),
                          "attacks": base["attacks"],
                          "breakdown": {k: round(v) for k, v in base["breakdown"].items()}}}
    if not total > 0:
        errors.append("a level 16 champion dealt no damage in 15 s")
    if not math.isclose(sum(base["breakdown"].values()), total, rel_tol=1e-6):
        errors.append("the breakdown does not add up to the total")
    prev, prev_d = 0.0, 0
    for d in (1, 2, 3, 4, 6, 8, 10, 12, 15):
        t = f.run(16, [], *big, float(d))["total"]
        if t < prev * (1 - 1e-9):
            errors.append(f"damage fell as the fight got longer: {prev:.0f} in {prev_d} s, {t:.0f} in {d} s")
            break
        prev, prev_d = t, d
    for item in ("rabadon's deathcap", "infinity edge", "nashor's tooth", "spear of shojin"):
        t = f.run(16, [item], *big, 15.0)["total"]
        if t < total * 0.999:
            errors.append(f"adding {item} lowered the damage ({total:.0f} -> {t:.0f})")
    unused = kit.get("unused") or {}
    labels = list(base["breakdown"])
    for slot in "QWER":
        values = ((dossier.get("abilities") or {}).get(slot) or {}).get("values") or []
        damaging = any(v.get("role") in ("damage", "dot", "onhit") and v.get("damageType")
                       for v in values if isinstance(v, dict))
        if damaging and slot not in unused and not any(l.upper().startswith(slot) for l in labels):
            errors.append(f"{slot} deals damage according to the dossier, but a 15 s level 16 fight "
                          f"shows no damage source starting with \"{slot}\" (sources: {labels}). "
                          f'Cast it under a label that starts with "{slot}", or, if it deals no damage of '
                          f'its own in this fight (it only upgrades or replaces other abilities, or needs '
                          f'another unit), say so in the kit: "unused": {{"{slot}": "why"}}. Do not rename '
                          f"another ability's damage to satisfy this.")
    dps = base["dps"]
    if not 40 <= dps <= 4000:
        errors.append(f"implausible naked level 16 DPS vs 100 resists: {dps:.0f}")
    # cast times: the opening read off fights of growing length, with the ult and without
    floors = cast_floors(kit, dossier, stats_slug)
    facts["castTimes"] = floors
    for ult in (True, False) if floors else ():
        landed = first_landings(lambda t: f.run(16, [], *big, t, use_ult=ult), floors)  # noqa: B023
        found = cast_time_errors(landed, floors, "opening with the ult" if ult else "the ult not used")
        if found:
            errors += found
            break
    # and the symptom itself: a full burst build must not kill in zero time
    for name, items in BURST_SETS.items():
        r = f.run(16, items, *PRESETS["squishy"][:3], 0.0)
        if r["ttk"] is not None:
            landed = ", ".join(f"{k} {v:.0f}" for k, v in r["breakdown"].items() if v > 0)
            errors.append(f"with {name} items the squishy ({PRESETS['squishy'][0]} HP) is dead at t = 0.00 s, "
                          f"before the clock has moved: {landed} all land in the first instant. Nothing "
                          "kills in zero time: casts go one after another, each keeping the champion "
                          "busy for its cast time (the guide's 'Cast times'), and damage the sources put "
                          "after a stated delay lands in an event at that time.")
            break
    return errors, facts


def check_roster():
    """{name: errors} for every admitted driver that fails the fight checks,
    against the engine that is built (run after the checks themselves change)."""
    import builds
    if builds.source_stale():
        raise SystemExit("engine/src (or builds.py) is newer than the built engine: the fights would "
                         "run drivers that are not the tree's. Run jobs/build-engine.sh builds first.")
    failed = {}
    for name in driver_names():
        slug = name[:-len("_blind")] if name.endswith("_blind") else name
        with open(os.path.join(BASE_DIR, "data", "builds", f"{name}.json")) as f:
            kit = json.load(f)
        with open(os.path.join(ks.DOSSIERS_DIR, f"{slug}.json")) as f:
            dossier = json.load(f)
        with open(os.path.join(GENERATED_DIR, f"{name}.rs")) as f:
            driver_rs = f.read()
        errors = lint_cast_times(kit, dossier, driver_rs, slug)
        errors += fight_checks(kit, slug, dossier)[0]
        if errors:
            failed[name] = errors
    return failed


def cmd_check(args):
    if args.so_dir:
        sys.path.insert(0, args.so_dir)
    sys.path.insert(1, BASE_DIR)
    if args.all:
        failed = check_roster()
        for name, errors in failed.items():
            print(f"{name}: {errors[0][:200]}" + (f" (+{len(errors) - 1} more)" if errors[1:] else ""))
        print(f"{len(failed)} of {len(driver_names())} drivers fail: {' '.join(failed) or '-'}")
        sys.exit(1 if failed else 0)
    if not args.name:
        raise SystemExit("name a driver, or pass --all")
    name = args.name
    kit_path = args.kit or os.path.join(BASE_DIR, "data", "builds", f"{name}.json")
    with open(kit_path) as f:
        kit = json.load(f)
    stats = args.stats_from or name
    with open(os.path.join(ks.DOSSIERS_DIR, f"{stats}.json")) as f:
        dossier = json.load(f)
    errors, facts = fight_checks(kit, stats, dossier)
    rs_path = args.driver or os.path.join(GENERATED_DIR, f"{name}.rs")
    if os.path.exists(rs_path):
        with open(rs_path) as f:
            errors = lint_cast_times(kit, dossier, f.read(), stats) + errors
    print(json.dumps({"ok": not errors, "errors": errors, "facts": facts}))
    sys.exit(0 if not errors else 1)


# ---------------------------------------------------------------------------
# write: the model writes a kit and a driver; candidates are built and checked
# in a private copy of the engine
# ---------------------------------------------------------------------------

def system_prompt():
    with open(GUIDE_PATH) as f:
        guide = f.read()
    with open(os.path.join(BASE_DIR, "data", "builds", "jax.json")) as f:
        jax_kit = json.load(f)
    for k in ("_provenance", "attack"):
        jax_kit.pop(k, None)
    with open(os.path.join(GENERATED_DIR, "jax.rs")) as f:
        jax_rs = f.read()
    return (guide + "\n\n## Reference: Jax (hand-written in this format; it passes every check)\n\n"
            "```json\n" + json.dumps(jax_kit, indent=1) + "\n```\n\n```rust\n" + jax_rs + "```\n")


def user_prompt(slug, name):
    src = ks.load_sources(slug)
    with open(os.path.join(ks.DOSSIERS_DIR, f"{slug}.json")) as f:
        dossier = json.load(f)
    for ab in (dossier.get("abilities") or {}).values():
        if isinstance(ab, dict):
            ab.pop("filledBy", None)
            ab.pop("binUnused", None)
    dossier.pop("filledBy", None)
    wiki = "\n\n".join(
        f"### {slot}: {a['name']} (flags: {json.dumps(a.get('flags', {}))})\n{a.get('wikitext', '')}"
        for slot in ks.SLOTS for a in src["wiki"]["abilities"][slot])
    attack = attack_block(slug)
    display = src["sheet"]["ddragon"]["name"]
    hint = ""
    tri = os.path.join(ks.SOURCES_DIR, ks.default_patch(), "_triage", "triage.json")
    if os.path.exists(tri):
        with open(tri) as f:
            t = json.load(f)["results"].get(slug)
        if t:
            hint = (f"An earlier triage judged most of this champion's damage to come from: "
                    f"{t.get('damageFrom')}.\n")
    return (f'Champion: {display}. Write the kit with "champion": "{name}" and the driver.\n'
            f"Base attack: windup fraction {attack['windupFraction']}, "
            f"{'ranged' if attack['ranged'] else 'melee'} (the script fills `attack`).\n{hint}\n"
            f"## Dossier\n\n{json.dumps(dossier, ensure_ascii=False)}\n\n"
            f"## Numbers sheet (Riot's game file)\n\n{ks.sheet_text(src)}\n\n"
            f"## Wiki templates\n\n{wiki}\n")


def call_model(args, system, user, cwd):
    cmd = [args.claude, "-p", "--model", args.model, "--effort", args.effort, "--tools", "",
           "--system-prompt", system, "--output-format", "json"]
    t0 = time.time()
    try:
        r = subprocess.run(cmd, input=user, capture_output=True, text=True, cwd=cwd,
                           timeout=args.timeout)
        o = json.loads(r.stdout)
    except subprocess.TimeoutExpired:
        return None, {"seconds": round(time.time() - t0, 1), "error": "timeout"}
    except json.JSONDecodeError:
        return None, {"seconds": round(time.time() - t0, 1),
                      "error": f"no JSON from the CLI: {(r.stdout + r.stderr)[:300]}"}
    usage = o.get("usage") or {}
    log = {"seconds": round(time.time() - t0, 1), "cost": o.get("total_cost_usd"),
           "in": sum(usage.get(k, 0) for k in ("input_tokens", "cache_creation_input_tokens",
                                               "cache_read_input_tokens")),
           "out": usage.get("output_tokens", 0)}
    if o.get("is_error"):
        log["error"] = str(o.get("result"))[:300]
        return None, log
    return o.get("result") or "", log


def parse_reply(text):
    kit_m = re.search(r"```json\s*\n(.*?)\n```", text, re.S)
    rs_m = re.search(r"```rust\s*\n(.*?)\n```", text, re.S)
    if not kit_m or not rs_m:
        raise ValueError("the reply needs one ```json block (the kit) and one ```rust block (the driver)")
    return json.loads(kit_m.group(1)), rs_m.group(1) + "\n"


def cargo(engine_dir, target_dir):
    """Build the engine copy; (ok, compiler output trimmed to its errors)."""
    env = dict(os.environ, CARGO_TARGET_DIR=target_dir,
               PYO3_PYTHON="/run/current-system/sw/bin/python3")
    manifest = os.path.join(engine_dir, "Cargo.toml")
    if shutil.which("cargo"):
        cmd = ["cargo", "build", "--release", "--manifest-path", manifest]
    else:
        cmd = ["nix-shell", "-p", "cargo", "rustc", "--run",
               f"cargo build --release --manifest-path {manifest}"]
    r = subprocess.run(cmd, capture_output=True, text=True, env=env)
    if r.returncode == 0:
        return True, ""
    blocks = re.split(r"\n(?=error)", r.stderr)
    errs = [b for b in blocks if b.startswith("error")]
    return False, "\n".join(errs)[:6000] or r.stderr[-3000:]


class Bench:
    """A private copy of the engine where one worker builds its candidates."""

    def __init__(self):
        self.root = tempfile.mkdtemp(prefix="kit-driver-")
        self.engine = os.path.join(self.root, "engine")
        shutil.copytree(ENGINE_DIR, self.engine, ignore=shutil.ignore_patterns("target"))
        self.target = os.path.join(self.root, "target")
        self.so_dir = os.path.join(self.root, "py")
        os.makedirs(self.so_dir)

    def evaluate(self, name, stats_slug, kit, driver_rs):
        """Problems with a candidate, as text for the model ('' when it passes), and facts."""
        gen = os.path.join(self.engine, "src", "generated")
        with open(os.path.join(gen, f"{name}.rs"), "w") as f:
            f.write(driver_rs)
        write_registry(gen)
        ok, out = cargo(self.engine, self.target)
        if not ok:
            return "The driver does not compile:\n\n" + out, {}
        shutil.copy(os.path.join(self.target, "release", "liblol_engine.so"),
                    os.path.join(self.so_dir, "lol_engine.abi3.so"))
        kit_path = os.path.join(self.root, f"{name}.json")
        with open(kit_path, "w") as f:
            json.dump(kit, f)
        try:
            r = subprocess.run([sys.executable, os.path.abspath(__file__), "check", name,
                                "--kit", kit_path, "--stats-from", stats_slug,
                                # the candidate's own driver, not the tree's: the checks that
                                # read the Rust would otherwise judge the admitted one
                                "--driver", os.path.join(gen, f"{name}.rs"),
                                "--so-dir", self.so_dir],
                               capture_output=True, text=True, timeout=300, cwd=BASE_DIR)
        except subprocess.TimeoutExpired:
            return "The fight checks did not finish in 300 s.", {}
        try:
            rep = json.loads(r.stdout.strip().splitlines()[-1])
        except (json.JSONDecodeError, IndexError):
            return f"The fight checks crashed:\n{(r.stderr or r.stdout)[-2500:]}", {}
        if rep["ok"]:
            return "", rep["facts"]
        return "The fights fail these checks:\n- " + "\n- ".join(rep["errors"]), rep.get("facts", {})

    def drop(self, name):
        path = os.path.join(self.engine, "src", "generated", f"{name}.rs")
        if os.path.exists(path):
            os.remove(path)

    def close(self):
        shutil.rmtree(self.root, ignore_errors=True)


REPAIR_NOTE = ("This kit and driver were admitted before the script checked what is listed below. "
               "Change what that takes and keep the rest of the rotation and every number as they "
               "are; bring the kit's notes in line with what the driver now does.\n\n")


def as_written(kit):
    """An admitted kit as the model wrote it: without what the script added."""
    never = {"attack": {"never": True}} if (kit.get("attack") or {}).get("never") else {}
    return dict({k: v for k, v in kit.items() if k not in ("_provenance", "manaless", "attack")},
                **never)


def admitted_files(name):
    with open(os.path.join(BASE_DIR, "data", "builds", f"{name}.json")) as f:
        kit = json.load(f)
    with open(os.path.join(GENERATED_DIR, f"{name}.rs")) as f:
        return kit, f.read()


def retry_prompt(slug, name, kit, driver_rs, problems, history):
    earlier = ("\n## What the earlier rounds failed on (do not go back to those)\n\n"
               + "\n".join(history[:-1]) + "\n") if len(history) > 1 else ""
    return (user_prompt(slug, name) + "\n## Your previous attempt\n\n```json\n"
            + json.dumps(kit, indent=1) + "\n```\n\n```rust\n" + (driver_rs or "") + "```\n\n"
            "## What is wrong with it\n\n" + problems + "\n" + earlier
            + "\nReply with both complete files again.")


def write_champion(args, slug, bench, cwd):
    name = f"{slug}_blind" if args.blind else slug
    t0 = time.time()
    ensure_snapshot(slug)
    known = source_numbers(slug)
    system, user = system_prompt(), user_prompt(slug, name)
    with open(os.path.join(ks.DOSSIERS_DIR, f"{slug}.json")) as f:
        dossier = json.load(f)
    calls, problems, kit, driver_rs, facts = [], "no reply", None, None, {}
    history = []  # what each earlier round failed on: a retry that only sees the last one can oscillate
    provenance = []
    if args.repair:
        # start from what is admitted: the checks it now fails are the first round's complaint
        on_disk, driver_rs = admitted_files(name)
        provenance = list(on_disk.get("_provenance") or [])
        kit = as_written(on_disk)
        full = dict(kit, attack=dict(attack_block(slug), **(kit.get("attack") or {})))
        static = lint_cast_times(kit, dossier, driver_rs, slug)
        if static:
            problems, facts = "The fights fail these checks:\n- " + "\n- ".join(static), {}
        else:
            problems, facts = bench.evaluate(name, slug, full, driver_rs)
        if not problems:
            say(f"{name}: passes the checks as it is, left alone")
            return {"name": name, "ok": True, "rounds": 0, "unchanged": True,
                    "seconds": round(time.time() - t0, 1), "costEquivalentUsd": 0}
        say(f"  {name} as admitted: {problems.splitlines()[-1][:110]}")
        history.append(f"as admitted: {problems.strip().splitlines()[-1][:300]}")
        user = retry_prompt(slug, name, kit, driver_rs, REPAIR_NOTE + problems, history)
    for rnd in range(1, args.rounds + 1):
        text, log = call_model(args, system, user, cwd)
        log["round"] = rnd
        calls.append(log)
        if text is None:
            problems = f"the model call failed: {log.get('error')}"
            if LIMIT.search(problems):
                if not _stop.is_set():
                    _stop.set()
                    say(f"STOPPING: {problems}")
                break
            # overloaded, rate-limited, a timeout: wait before the next round
            say(f"  {name} round {rnd}: {problems[:120]}; pausing")
            if _stop.wait(60 * rnd):
                break
            continue
        try:
            kit, driver_rs = parse_reply(text)
            static = (lint_kit(kit, name, known) + lint_driver(driver_rs)
                      + lint_cast_times(kit, dossier, driver_rs, slug))
            if static:
                problems = "Fix these before it is compiled:\n- " + "\n- ".join(static)
            else:
                full = dict(kit, attack=dict(attack_block(slug), **(kit.get("attack") or {})))
                problems, facts = bench.evaluate(name, slug, full, driver_rs)
        except (ValueError, json.JSONDecodeError) as e:
            problems = f"Your reply could not be read: {e}"
        log["problems"] = problems[:1500]
        say(f"  {name} round {rnd}: {'passes' if not problems else problems.splitlines()[0][:110]}")
        if not problems:
            break
        history.append(f"round {rnd}: {problems.strip().splitlines()[-1][:300]}")
        user = retry_prompt(slug, name, kit, driver_rs, problems, history)
    summary = {"name": name, "ok": not problems, "rounds": len(calls),
               "seconds": round(time.time() - t0, 1),
               "tokensIn": sum(c.get("in", 0) for c in calls),
               "tokensOut": sum(c.get("out", 0) for c in calls),
               "costEquivalentUsd": round(sum(c.get("cost") or 0 for c in calls), 3),
               "facts": facts, "problems": problems[:2000]}
    log_dir = os.path.join(BASE_DIR, ".cache", "kit-driver")
    os.makedirs(log_dir, exist_ok=True)
    ks.write_json(os.path.join(log_dir, f"{name}.json"), {"summary": summary, "calls": calls})
    if summary["ok"]:
        # admitted: into the tree (the registry and the engine are rebuilt once, at the end)
        full = dict(kit, attack=dict(attack_block(slug), **(kit.get("attack") or {})))
        if args.repair:
            full["_provenance"] = provenance + [
                f"Repaired by jobs/kit_driver.py --repair ({args.model}, {time.strftime('%Y-%m-%d')}): "
                "the admitted kit and driver went back to the model with the fight checks they had "
                "come to fail; compiled and passed them; NOT reviewed by a person."]
        else:
            full["_provenance"] = [
                f"Machine-written by jobs/kit_driver.py ({args.model}, {time.strftime('%Y-%m-%d')}) "
                f"from data/builds/dossiers/{slug}.json and the archived sources; compiled and passed "
                "the fight checks; NOT reviewed by a person. The driver is "
                f"engine/src/generated/{name}.rs."]
        if is_manaless(slug):
            full["manaless"] = True
        ks.write_json(os.path.join(BASE_DIR, "data", "builds", f"{name}.json"), full)
        with open(os.path.join(GENERATED_DIR, f"{name}.rs"), "w") as f:
            f.write(driver_rs)
    else:
        bench.drop(name)
        if kit is not None:  # keep the last attempt for whoever looks into it
            ks.write_json(os.path.join(log_dir, f"{name}.kit.json"), kit)
            with open(os.path.join(log_dir, f"{name}.rs"), "w") as f:
                f.write(driver_rs or "")
    say(f"{name}: {'ADMITTED' if summary['ok'] else 'REJECTED'} after {summary['rounds']} round(s), "
        f"{summary['seconds']} s, {summary['tokensIn']} in / {summary['tokensOut']} out, "
        f"${summary['costEquivalentUsd']}")
    return summary


_stop = threading.Event()  # the plan's usage limit, or a logged-out CLI: end the run
LIMIT = re.compile(r"(usage|session|weekly|5[- ]hour|hour)\s+limit|limit reached|"
                   r"hit your .{0,40}limit|out of (extra )?usage|not logged in|/login", re.I)


def admitted(name):
    return (os.path.exists(os.path.join(GENERATED_DIR, f"{name}.rs"))
            and os.path.exists(os.path.join(BASE_DIR, "data", "builds", f"{name}.json")))


def all_slugs():
    """Every champion with a dossier and no hand-written driver, the simplest
    kits first (the triage's primitive count; champion-specific logic last)."""
    slugs = sorted(f[:-5] for f in os.listdir(ks.DOSSIERS_DIR) if f.endswith(".json"))
    slugs = [s for s in slugs if s not in HAND_WRITTEN + RESERVED and s != "jax"]
    tri = os.path.join(ks.SOURCES_DIR, ks.default_patch(), "_triage", "triage.json")
    if os.path.exists(tri):
        with open(tri) as f:
            results = json.load(f)["results"]
        slugs.sort(key=lambda s: (int(bool(results.get(s, {}).get("needsBespoke", True))),
                                  len(results.get(s, {}).get("primitives") or [0] * 99), s))
    return slugs


def cmd_write(args):
    slugs = all_slugs() if args.all else [s.lower() for s in args.slugs]
    if args.failing:
        args.repair = True
        slugs = [n for n in check_roster() if n != "jax" and not n.endswith("_blind")]
        say(f"{len(slugs)} admitted drivers fail the checks: {' '.join(slugs) or '-'}")
    if not slugs:
        raise SystemExit("name champions, or pass --all or --failing")
    if not args.blind:
        clash = [s for s in slugs if s in HAND_WRITTEN or s == "jax"]
        if clash:
            raise SystemExit(f"{clash} have hand-written drivers: use --blind to write a second one")
    if args.repair:
        missing = [s for s in slugs if not admitted(f"{s}_blind" if args.blind else s)]
        if missing:
            raise SystemExit(f"--repair starts from an admitted driver; none for {missing}")
    elif not args.blind and not args.force:
        done = [s for s in slugs if admitted(s)]
        slugs = [s for s in slugs if s not in done]
        if done:
            say(f"{len(done)} already admitted, skipped (--force rewrites them)")
    if not slugs:
        print("nothing to do")
        return
    cwd = tempfile.mkdtemp(prefix="kit-driver-cwd-")
    benches = [Bench() for _ in range(min(args.workers, len(slugs)))]
    free = list(benches)
    lock = threading.Lock()

    def job(slug):
        if _stop.is_set():
            return {"name": slug, "ok": False, "problems": "not started: the run was stopped"}
        with lock:
            bench = free.pop()
        try:
            return write_champion(args, slug, bench, cwd)
        except BaseException as e:
            say(f"{slug}: crashed: {type(e).__name__}: {e}")
            return {"name": slug, "ok": False, "problems": str(e)}
        finally:
            with lock:
                free.append(bench)

    try:
        with concurrent.futures.ThreadPoolExecutor(max_workers=len(benches)) as pool:
            results = list(pool.map(job, slugs))
    finally:
        for b in benches:
            b.close()
        shutil.rmtree(cwd, ignore_errors=True)
    names = write_registry()
    ok = [r["name"] for r in results if r["ok"]]
    same = [r["name"] for r in results if r.get("unchanged")]
    cost = sum(r.get("costEquivalentUsd", 0) for r in results)
    print(f"admitted {len(ok) - len(same)}/{len(results) - len(same)}: "
          f"{', '.join(n for n in ok if n not in same) or '-'}; "
          f"rejected: {', '.join(r['name'] for r in results if not r['ok']) or '-'}; "
          + (f"already passing, left alone: {', '.join(same)}; " if same else "")
          + f"${cost:.2f} cost-equivalent")
    print(f"registry: {len(names)} generated drivers. Rebuild the engine: jobs/build-engine.sh builds")
    if _stop.is_set():
        print("stopped at the plan's usage limit: run the same command again to resume")
        sys.exit(75)
    sys.exit(0 if len(ok) == len(results) else 1)


# ---------------------------------------------------------------------------
# compare: a blind driver against the hand-written one
# ---------------------------------------------------------------------------

def ranks_of(xs):
    order = sorted(range(len(xs)), key=lambda i: xs[i])
    out, i = [0.0] * len(xs), 0
    while i < len(order):
        j = i
        while j + 1 < len(order) and xs[order[j + 1]] == xs[order[i]]:
            j += 1
        for k in range(i, j + 1):
            out[order[k]] = (i + j) / 2.0
        i = j + 1
    return out


def spearman(a, b):
    ra, rb = ranks_of(a), ranks_of(b)
    ma, mb = sum(ra) / len(ra), sum(rb) / len(rb)
    cov = sum((x - ma) * (y - mb) for x, y in zip(ra, rb))
    va, vb = sum((x - ma) ** 2 for x in ra), sum((y - mb) ** 2 for y in rb)
    return cov / math.sqrt(va * vb) if va and vb else float("nan")


def median(xs):
    xs = sorted(xs)
    return xs[len(xs) // 2] if xs else float("nan")


def cmd_compare(args):
    sys.path.insert(0, BASE_DIR)
    import builds
    slug, name = args.slug, f"{args.slug}_blind"
    hand, blind = Fights(builds.load_kit(slug), slug), Fights(builds.load_kit(name), slug)
    rng = random.Random(7)
    pool_ids = [i for i in builds.DEFAULT_POOL if i in hand.pool]
    sample = [[rng.choice(builds.BOOTS)] + rng.sample(pool_ids, 5) for _ in range(args.n)]
    report = {}
    for pname, (hp, ar, mr, dur) in PRESETS.items():
        rows = []
        for items in sample:
            a = hand.run(16, items, hp, ar, mr, dur)
            b = blind.run(16, items, hp, ar, mr, dur)
            score = lambda r: r["ttk"] if r["ttk"] is not None else dur * (1 + r["hp_left"] / hp)  # noqa: E731
            rows.append((a["total"], b["total"], a["ttk"], b["ttk"], score(a), score(b)))
        k = max(5, args.n // 10)
        top_a = set(sorted(range(len(rows)), key=lambda i: rows[i][4])[:k])
        top_b = set(sorted(range(len(rows)), key=lambda i: rows[i][5])[:k])
        both = [(r[2], r[3]) for r in rows if r[2] is not None and r[3] is not None]
        report[pname] = {
            "spearman": round(spearman([r[4] for r in rows], [r[5] for r in rows]), 3),
            f"top{k}Overlap": len(top_a & top_b),
            "bestBuildRankInBlind": sorted(range(len(rows)), key=lambda i: rows[i][5]).index(
                min(range(len(rows)), key=lambda i: rows[i][4])) + 1,
            "medianDamageRatio": round(median([r[1] / r[0] for r in rows if r[0] > 0]), 3),
            "kills": [sum(r[2] is not None for r in rows), sum(r[3] is not None for r in rows)],
            "medianKillTimeRatio": round(median([b / a for a, b in both]), 3) if both else None,
        }
    naked_a = hand.run(16, [], 30_000, 100, 100, 15.0)
    naked_b = blind.run(16, [], 30_000, 100, 100, 15.0)
    report["naked15s"] = {"hand": {k: round(v) for k, v in naked_a["breakdown"].items()},
                          "blind": {k: round(v) for k, v in naked_b["breakdown"].items()},
                          "attacks": [naked_a["attacks"], naked_b["attacks"]]}
    print(json.dumps(report, indent=1))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sp = sub.add_parser("registry")
    sp.set_defaults(func=cmd_registry)
    sp = sub.add_parser("annotate")
    sp.set_defaults(func=cmd_annotate)
    sp = sub.add_parser("write")
    sp.add_argument("slugs", nargs="*")
    sp.add_argument("--all", action="store_true",
                    help="every champion with a dossier and no hand-written driver")
    sp.add_argument("--force", action="store_true", help="rewrite admitted drivers from scratch")
    sp.add_argument("--repair", action="store_true",
                    help="start from the admitted kit and driver: what they fail goes to the model\n"
                         "as the first round's complaint; one that passes is left alone")
    sp.add_argument("--failing", action="store_true",
                    help="--repair every admitted driver that fails the checks (`check --all`)")
    sp.add_argument("--blind", action="store_true",
                    help="write <slug>_blind beside a hand-written driver, for comparison")
    sp.add_argument("--workers", type=int, default=3)
    sp.add_argument("--model", default="sonnet")
    sp.add_argument("--effort", default="medium")
    sp.add_argument("--rounds", type=int, default=5, help="model calls per champion at most")
    sp.add_argument("--timeout", type=int, default=1800, help="seconds per model call")
    sp.add_argument("--claude", default=shutil.which("claude") or "claude")
    sp.set_defaults(func=cmd_write)
    sp = sub.add_parser("compare")
    sp.add_argument("slug")
    sp.add_argument("--n", type=int, default=120, help="item builds sampled")
    sp.set_defaults(func=cmd_compare)
    sp = sub.add_parser("check")
    sp.add_argument("name", nargs="?")
    sp.add_argument("--all", action="store_true",
                    help="every admitted driver, against the engine that is built")
    sp.add_argument("--kit", help="kit file (default data/builds/<name>.json)")
    sp.add_argument("--stats-from", help="the champion whose base stats and dossier apply")
    sp.add_argument("--so-dir", help="directory holding the lol_engine build to test")
    sp.add_argument("--driver", help="driver file (default engine/src/generated/<name>.rs)")
    sp.set_defaults(func=cmd_check)
    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
